"""Utilities for comparing gene/GPCR expression in clozapine-responsive cells.

This module is intentionally notebook-friendly: the main entry point,
``run_clz_response_expression_analysis``, accepts the ``adata`` object used in the
mouse mPFC notebooks plus the receptor-affinity matrix (``D_R_mtx``), performs
Clozapine-responsive vs. non-responsive expression comparisons, writes summary
CSV files, and saves publication-editable PDF figures.
"""

from __future__ import annotations

import os
import re
from collections.abc import Iterable
from dataclasses import dataclass

import anndata
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import sparse, stats
from statsmodels.stats.multitest import multipletests


GPCR_SYMBOL_PATTERN = re.compile(
    r"^(?:"
    r"GPR\d+[A-Z]?|GPRC\d?[A-Z]\d?|GPER\d?|"
    r"ADRA\d[A-Z]|ADRB\d|CHRM\d|DRD\d|HRH\d|HTR\d[A-Z]?|"
    r"ADORA\d[A-Z]?|ADGR[A-Z]\d+|AGTR\d[A-Z]?|AVPR\d[A-Z]?|BDKRB\d|"
    r"CALCRL?|CNR\d|CXCR\d|CCR\d|FPR\d|FFAR\d|GALR\d|GABBR\d|"
    r"LPA\d|LPAR\d|MC\dR|MCHR\d|NPY\dR|OPR[A-Z]\d|OXTR|SSTR\d|TACR\d|"
    r"PTGER\d|PTGFR|PTGIR|PTGDR\d?|PTGIR|P2RY\d+|S1PR\d|TAAR\d+[A-Z]?|"
    r"VIPR\d|NPFFR\d|NTSR\d|APLNR|C3AR\d|C5AR\d|CASR|EDNR[A-Z]|GCGR|GLP\dR"
    r")$"
)


@dataclass(frozen=True)
class ClzExpressionAnalysisResult:
    """Paths and tables generated by ``run_clz_response_expression_analysis``."""

    output_dir: str
    bdnf_stats: pd.DataFrame
    matrix_gpcr_stats: pd.DataFrame
    all_gpcr_stats: pd.DataFrame
    outside_matrix_gpcr_stats: pd.DataFrame


def _as_bool_mask(values: pd.Series, positive_label=True) -> pd.Series:
    """Return a boolean mask from common notebook encodings of a group column."""
    if values.dtype.name == "category":
        values = values.astype(str)
    if values.dtype == bool:
        return values == bool(positive_label)

    positive_strings = {"true", "1", "yes", "y", "clz", "clozapine", "selective", "responsive"}
    negative_strings = {"false", "0", "no", "n", "nonresponsive", "non_responsive"}

    if isinstance(positive_label, str):
        return values.astype(str) == positive_label
    if isinstance(positive_label, (int, float, np.integer, np.floating)) and positive_label not in (True, False):
        return values.astype(float) == float(positive_label)

    lowered = values.astype(str).str.lower()
    if bool(positive_label):
        return lowered.isin(positive_strings)
    return lowered.isin(negative_strings)


def _deduplicate_upper(items: Iterable[str]) -> list[str]:
    """Upper-case symbols while preserving first occurrence order."""
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        item_upper = str(item).upper()
        if item_upper not in seen:
            seen.add(item_upper)
            result.append(item_upper)
    return result


def _adata_gene_lookup(adata: anndata.AnnData) -> dict[str, str]:
    """Map upper-case gene symbols to the exact ``adata.var_names`` entry."""
    lookup: dict[str, str] = {}
    for var_name in adata.var_names:
        lookup.setdefault(str(var_name).upper(), str(var_name))
    return lookup


def _obs_raw_lookup(adata: anndata.AnnData, raw_suffix: str = "_raw") -> dict[str, str]:
    """Map upper-case symbols to exact raw-expression columns in ``adata.obs``."""
    lookup: dict[str, str] = {}
    for col in adata.obs.columns:
        col_str = str(col)
        if col_str.upper().endswith(raw_suffix.upper()):
            symbol = col_str[: -len(raw_suffix)].upper()
            lookup.setdefault(symbol, col_str)
    return lookup


def _extract_var_expression(adata: anndata.AnnData, var_name: str) -> np.ndarray:
    """Extract one gene vector from ``adata.X`` as a dense 1D numpy array."""
    gene_idx = adata.var_names.get_loc(var_name)
    vector = adata.X[:, gene_idx]
    if sparse.issparse(vector):
        vector = vector.toarray()
    return np.asarray(vector).ravel()


def expression_dataframe(
    adata: anndata.AnnData,
    genes: Iterable[str],
    raw_suffix: str = "_raw",
    prefer_obs_raw: bool = True,
) -> tuple[pd.DataFrame, list[str]]:
    """Build a cell-by-gene expression table for genes available in the AnnData.

    The notebooks store marker/receptor raw counts in ``adata.obs`` as
    ``<GENE>_raw``. Those columns are preferred because ``adata.X`` may contain
    scaled/HVG-filtered values. If a raw column is absent, this function falls
    back to ``adata.X`` when the gene is present in ``adata.var_names``.
    """
    genes_upper = _deduplicate_upper(genes)
    var_lookup = _adata_gene_lookup(adata)
    obs_lookup = _obs_raw_lookup(adata, raw_suffix=raw_suffix)

    data: dict[str, np.ndarray] = {}
    missing: list[str] = []
    for gene in genes_upper:
        if prefer_obs_raw and gene in obs_lookup:
            data[gene] = pd.to_numeric(adata.obs[obs_lookup[gene]], errors="coerce").to_numpy(dtype=float)
        elif gene in var_lookup:
            data[gene] = _extract_var_expression(adata, var_lookup[gene]).astype(float)
        elif not prefer_obs_raw and gene in obs_lookup:
            data[gene] = pd.to_numeric(adata.obs[obs_lookup[gene]], errors="coerce").to_numpy(dtype=float)
        else:
            missing.append(gene)

    expr = pd.DataFrame(data, index=adata.obs_names)
    return expr, missing


def find_gpcr_genes_in_adata(
    adata: anndata.AnnData,
    extra_genes: Iterable[str] | None = None,
    raw_suffix: str = "_raw",
) -> list[str]:
    """Infer GPCR-like genes available in ``adata`` from raw columns and var names."""
    candidates = [str(v).upper() for v in adata.var_names]
    candidates.extend(_obs_raw_lookup(adata, raw_suffix=raw_suffix).keys())
    if extra_genes is not None:
        candidates.extend(str(g).upper() for g in extra_genes)
    return [gene for gene in _deduplicate_upper(candidates) if GPCR_SYMBOL_PATTERN.match(gene)]


def compare_expression_between_groups(
    expr_df: pd.DataFrame,
    group_mask: pd.Series | np.ndarray,
    group_name: str = "clz_responsive",
    reference_name: str = "non_responsive",
) -> pd.DataFrame:
    """Compare each expression column between responsive and non-responsive cells."""
    mask = np.asarray(group_mask, dtype=bool)
    rows: list[dict[str, float | str | int]] = []
    for gene in expr_df.columns:
        selected = pd.to_numeric(expr_df.loc[mask, gene], errors="coerce").dropna().to_numpy(dtype=float)
        reference = pd.to_numeric(expr_df.loc[~mask, gene], errors="coerce").dropna().to_numpy(dtype=float)

        if selected.size == 0 or reference.size == 0:
            p_value = np.nan
            u_stat = np.nan
        else:
            u_stat, p_value = stats.mannwhitneyu(selected, reference, alternative="two-sided")

        selected_mean = float(np.nanmean(selected)) if selected.size else np.nan
        reference_mean = float(np.nanmean(reference)) if reference.size else np.nan
        selected_median = float(np.nanmedian(selected)) if selected.size else np.nan
        reference_median = float(np.nanmedian(reference)) if reference.size else np.nan
        log2fc = np.log2((selected_mean + 1e-9) / (reference_mean + 1e-9))
        rows.append(
            {
                "gene": gene,
                f"n_{group_name}": int(selected.size),
                f"n_{reference_name}": int(reference.size),
                f"mean_{group_name}": selected_mean,
                f"mean_{reference_name}": reference_mean,
                f"median_{group_name}": selected_median,
                f"median_{reference_name}": reference_median,
                f"pct_expr_{group_name}": float(np.mean(selected > 0) * 100) if selected.size else np.nan,
                f"pct_expr_{reference_name}": float(np.mean(reference > 0) * 100) if reference.size else np.nan,
                "mean_diff": selected_mean - reference_mean,
                "log2FC_mean": float(log2fc),
                "mannwhitneyu": float(u_stat) if not np.isnan(u_stat) else np.nan,
                "p_value": float(p_value) if not np.isnan(p_value) else np.nan,
            }
        )

    result_columns = [
        "gene",
        f"n_{group_name}",
        f"n_{reference_name}",
        f"mean_{group_name}",
        f"mean_{reference_name}",
        f"median_{group_name}",
        f"median_{reference_name}",
        f"pct_expr_{group_name}",
        f"pct_expr_{reference_name}",
        "mean_diff",
        "log2FC_mean",
        "mannwhitneyu",
        "p_value",
        "p_adj_bh",
    ]
    stats_df = pd.DataFrame(rows)
    if stats_df.empty:
        return pd.DataFrame(columns=result_columns)

    valid = stats_df["p_value"].notna()
    stats_df["p_adj_bh"] = np.nan
    if valid.any():
        stats_df.loc[valid, "p_adj_bh"] = multipletests(stats_df.loc[valid, "p_value"], method="fdr_bh")[1]
    return stats_df.reindex(columns=result_columns).sort_values(["p_adj_bh", "p_value", "gene"], na_position="last").reset_index(drop=True)


def _plot_bdnf(expr_df: pd.DataFrame, mask: pd.Series, output_path: str) -> None:
    plot_df = pd.DataFrame(
        {
            "group": np.where(mask.to_numpy(dtype=bool), "Clozapine-responsive", "Non-responsive"),
            "BDNF expression": expr_df["BDNF"].to_numpy(dtype=float),
        }
    )
    fig, ax = plt.subplots(figsize=(4.2, 4.0))
    sns.violinplot(data=plot_df, x="group", y="BDNF expression", inner=None, cut=0, ax=ax, palette=["#d62728", "#7f7f7f"])
    sns.boxplot(data=plot_df, x="group", y="BDNF expression", width=0.25, showfliers=False, ax=ax, color="white")
    ax.set_xlabel("")
    ax.tick_params(axis="x", rotation=20)
    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)


def _plot_top_gpcr_heatmap(stats_df: pd.DataFrame, output_path: str, top_n: int = 30) -> None:
    if stats_df.empty:
        return
    selected = stats_df.reindex(stats_df["log2FC_mean"].abs().sort_values(ascending=False).index).head(top_n)
    heat = selected.set_index("gene")[["log2FC_mean"]]
    fig_height = max(4.0, 0.28 * len(heat) + 1.5)
    fig, ax = plt.subplots(figsize=(3.4, fig_height))
    vmax = max(1e-9, np.nanmax(np.abs(heat.to_numpy())))
    sns.heatmap(heat, cmap="bwr", center=0, vmin=-vmax, vmax=vmax, annot=True, fmt=".2f", cbar_kws={"label": "log2FC mean"}, ax=ax)
    ax.set_ylabel("GPCR")
    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)


def _plot_gpcr_volcano(stats_df: pd.DataFrame, output_path: str, title: str) -> None:
    if stats_df.empty:
        return
    plot_df = stats_df.copy()
    plot_df["neg_log10_p_adj"] = -np.log10(plot_df["p_adj_bh"].fillna(1.0).clip(lower=1e-300))
    plot_df["significant"] = plot_df["p_adj_bh"] < 0.05

    fig, ax = plt.subplots(figsize=(6.0, 4.8))
    sns.scatterplot(data=plot_df, x="log2FC_mean", y="neg_log10_p_adj", hue="significant", palette={True: "#d62728", False: "#7f7f7f"}, ax=ax, legend=False)
    top_labels = plot_df.sort_values("p_adj_bh", na_position="last").head(12)
    for _, row in top_labels.iterrows():
        ax.text(row["log2FC_mean"], row["neg_log10_p_adj"], row["gene"], fontsize=8)
    ax.axhline(-np.log10(0.05), color="black", linewidth=0.8, linestyle="--")
    ax.axvline(0, color="black", linewidth=0.8)
    ax.set_title(title)
    ax.set_xlabel("log2FC mean (responsive / non-responsive)")
    ax.set_ylabel("-log10(FDR)")
    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)


def run_clz_response_expression_analysis(
    adata: anndata.AnnData,
    D_R_mtx: pd.DataFrame,
    group_col: str = "is_clz_selective",
    positive_label=True,
    output_dir: str = "/data/figures/clz_response_expression",
    all_gpcr_genes: Iterable[str] | None = None,
    raw_suffix: str = "_raw",
    top_n_plot: int = 30,
) -> ClzExpressionAnalysisResult:
    """Run BDNF and GPCR expression comparisons and save CSV/PDF outputs."""
    if group_col not in adata.obs.columns:
        raise KeyError(f"{group_col} is not present in adata.obs")

    os.makedirs(output_dir, exist_ok=True)
    plt.rcParams["pdf.fonttype"] = 42
    plt.rcParams["ps.fonttype"] = 42
    plt.rcParams["font.family"] = "DejaVu Sans"
    sns.set_style("whitegrid")

    clz_mask = _as_bool_mask(adata.obs[group_col], positive_label=positive_label)
    if clz_mask.sum() == 0 or (~clz_mask).sum() == 0:
        raise ValueError(f"{group_col} must contain both responsive and non-responsive cells")

    bdnf_expr, missing_bdnf = expression_dataframe(adata, ["BDNF"], raw_suffix=raw_suffix)
    if missing_bdnf:
        bdnf_stats = pd.DataFrame({"gene": ["BDNF"], "status": ["missing_from_adata"]})
    else:
        bdnf_stats = compare_expression_between_groups(bdnf_expr, clz_mask)
        _plot_bdnf(bdnf_expr, clz_mask, os.path.join(output_dir, "bdnf_clz_responsive_vs_nonresponsive.pdf"))
    bdnf_stats.to_csv(os.path.join(output_dir, "bdnf_clz_responsive_vs_nonresponsive.csv"), index=False)

    matrix_gpcr_genes = _deduplicate_upper(D_R_mtx.columns)
    matrix_gpcr_expr, missing_matrix_gpcr = expression_dataframe(adata, matrix_gpcr_genes, raw_suffix=raw_suffix)
    matrix_gpcr_stats = compare_expression_between_groups(matrix_gpcr_expr, clz_mask)
    matrix_gpcr_stats["in_affinity_matrix"] = True
    if missing_matrix_gpcr:
        missing_rows = pd.DataFrame({"gene": missing_matrix_gpcr, "status": "missing_from_adata", "in_affinity_matrix": True})
        matrix_gpcr_stats = pd.concat([matrix_gpcr_stats, missing_rows], ignore_index=True)
    matrix_gpcr_stats.to_csv(os.path.join(output_dir, "affinity_matrix_gpcr_clz_responsive_vs_nonresponsive.csv"), index=False)
    _plot_top_gpcr_heatmap(matrix_gpcr_stats.dropna(subset=["log2FC_mean"]), os.path.join(output_dir, "affinity_matrix_gpcr_log2fc_heatmap.pdf"), top_n=top_n_plot)
    _plot_gpcr_volcano(matrix_gpcr_stats.dropna(subset=["log2FC_mean"]), os.path.join(output_dir, "affinity_matrix_gpcr_volcano.pdf"), "Affinity-matrix GPCRs")

    inferred_gpcr_genes = find_gpcr_genes_in_adata(adata, extra_genes=all_gpcr_genes, raw_suffix=raw_suffix)
    combined_gpcr_genes = _deduplicate_upper([*matrix_gpcr_genes, *inferred_gpcr_genes])
    all_gpcr_expr, missing_all_gpcr = expression_dataframe(adata, combined_gpcr_genes, raw_suffix=raw_suffix)
    all_gpcr_stats = compare_expression_between_groups(all_gpcr_expr, clz_mask)
    all_gpcr_stats["in_affinity_matrix"] = all_gpcr_stats["gene"].isin(matrix_gpcr_genes)
    if missing_all_gpcr:
        missing_rows = pd.DataFrame(
            {
                "gene": missing_all_gpcr,
                "status": "missing_from_adata",
                "in_affinity_matrix": [gene in matrix_gpcr_genes for gene in missing_all_gpcr],
            }
        )
        all_gpcr_stats = pd.concat([all_gpcr_stats, missing_rows], ignore_index=True)
    all_gpcr_stats.to_csv(os.path.join(output_dir, "all_detected_gpcr_clz_responsive_vs_nonresponsive.csv"), index=False)
    _plot_gpcr_volcano(all_gpcr_stats.dropna(subset=["log2FC_mean"]), os.path.join(output_dir, "all_detected_gpcr_volcano.pdf"), "All detected GPCR-like genes")

    outside_matrix_gpcr_stats = all_gpcr_stats[all_gpcr_stats["in_affinity_matrix"] == False].copy()
    outside_matrix_gpcr_stats.to_csv(os.path.join(output_dir, "outside_matrix_gpcr_clz_responsive_vs_nonresponsive.csv"), index=False)
    _plot_top_gpcr_heatmap(outside_matrix_gpcr_stats.dropna(subset=["log2FC_mean"]), os.path.join(output_dir, "outside_matrix_gpcr_log2fc_heatmap.pdf"), top_n=top_n_plot)

    print(f"Saved clozapine-response expression analysis to: {output_dir}")
    print("BDNF:")
    print(bdnf_stats.head())
    print("Affinity-matrix GPCRs:")
    print(matrix_gpcr_stats.head(10))
    print("All detected GPCR-like genes:")
    print(all_gpcr_stats.head(10))

    return ClzExpressionAnalysisResult(
        output_dir=output_dir,
        bdnf_stats=bdnf_stats,
        matrix_gpcr_stats=matrix_gpcr_stats,
        all_gpcr_stats=all_gpcr_stats,
        outside_matrix_gpcr_stats=outside_matrix_gpcr_stats,
    )
