"""Notebook-friendly figure helpers for clozapine-responsive cell characterization.

This module is designed for interactive use from an ipynb after running the
preprocessing / drug-response workflow.  It prints a conversation-style figure
plan and, when enough annotations are present, creates the core tables/plots for
answering two distinct questions:

1. What are clozapine-responsive cells? (UMAP, cell type enrichment, layer markers)
2. Why are they pharmacologically recruitable? (receptor/cAMP signatures,
   synapse/plasticity gene-set summaries)

Example
-------
>>> import clz_responsive_figure_analysis as clzfig
>>> result = clzfig.run_clz_responsive_figure_story(
...     adata,
...     cell_type_col="cell_type",
...     output_dir="outputs/clz_responsive_figures",
... )
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import anndata
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import sparse, stats


DEFAULT_LAYER_MARKERS = {
    "pan_excitatory": ["SLC17A7", "CAMK2A", "SATB2"],
    "inhibitory": ["GAD1", "GAD2"],
    "L2_3_IT": ["CUX2", "LINC00507", "SATB2"],
    "L4_5_IT": ["RORB"],
    "L5_IT_PT": ["BCL11B", "FEZF2"],
    "L6_CT": ["FOXP2", "TLE4", "TBR1"],
}

DEFAULT_RECEPTOR_MARKERS = {
    "5HT1A_M2_H3": ["HTR1A", "CHRM2", "HRH3"],
    "cAMP_related": ["ADRB1", "ADRB2", "DRD1", "DRD2", "HTR6", "HTR7"],
}

DEFAULT_FUNCTIONAL_GENESETS = {
    "glutamatergic_synapse": ["SLC17A7", "GRIN1", "GRIN2A", "GRIN2B", "GRIA1", "GRIA2", "DLG4"],
    "postsynaptic_density": ["DLG4", "SHANK2", "SHANK3", "HOMER1", "CAMK2A", "SYNGAP1"],
    "dendritic_spine_plasticity": ["ARC", "EGR1", "FOS", "BDNF", "CAMK2A", "NTRK2", "RGS4"],
    "cAMP_signaling": ["ADCY1", "ADCY8", "PRKACA", "PRKACB", "CREB1", "PDE4B", "PDE10A"],
}


@dataclass(frozen=True)
class ClzResponsiveFigureResult:
    """Tables generated by ``run_clz_responsive_figure_story``."""

    output_dir: str
    figure_plan: pd.DataFrame
    cell_type_enrichment: pd.DataFrame
    marker_dotplot: pd.DataFrame
    receptor_signature: pd.DataFrame
    functional_gene_sets: pd.DataFrame


def _print_dialogue(message: str) -> None:
    """Print a notebook-friendly dialogue block."""
    print(f"\n💬 {message}\n")


def _as_bool_mask(values: pd.Series, positive_label=True) -> pd.Series:
    """Convert common clozapine-responsive encodings to a boolean mask."""
    if values.dtype.name == "category":
        if positive_label in values.cat.categories:
            return values == positive_label
        values = values.astype(str)

    if values.dtype == bool:
        return values == bool(positive_label)

    if isinstance(positive_label, str):
        return values.astype(str) == positive_label

    lowered = values.astype(str).str.lower()
    if bool(positive_label):
        return lowered.isin({"true", "1", "yes", "y", "clz", "selective", "responsive"})
    return lowered.isin({"false", "0", "no", "n", "nonresponsive", "non_responsive"})


def _gene_lookup(adata: anndata.AnnData) -> dict[str, str]:
    """Map upper-case gene symbols to exact AnnData var names."""
    lookup: dict[str, str] = {}
    for gene in adata.var_names:
        lookup.setdefault(str(gene).upper(), str(gene))
    return lookup


def _raw_obs_lookup(adata: anndata.AnnData, raw_suffix: str = "_raw") -> dict[str, str]:
    """Map upper-case gene symbols to exact ``adata.obs`` raw-expression columns."""
    lookup: dict[str, str] = {}
    for col in adata.obs.columns:
        col_str = str(col)
        if col_str.upper().endswith(raw_suffix.upper()):
            lookup.setdefault(col_str[: -len(raw_suffix)].upper(), col_str)
    return lookup


def _matrix_column(matrix, idx: int) -> np.ndarray:
    """Return one matrix column as dense 1D array."""
    col = matrix[:, idx]
    if sparse.issparse(col):
        col = col.toarray()
    return np.asarray(col).ravel()


def expression_vector(
    adata: anndata.AnnData,
    gene: str,
    layer: str | None = "lognorm",
    prefer_obs_raw: bool = False,
) -> np.ndarray | None:
    """Extract one gene vector from a layer, ``adata.X``, or ``adata.obs[GENE_raw]``.

    Returns ``None`` when the gene is unavailable.
    """
    gene_upper = str(gene).upper()
    raw_lookup = _raw_obs_lookup(adata)
    var_lookup = _gene_lookup(adata)

    if prefer_obs_raw and gene_upper in raw_lookup:
        return pd.to_numeric(adata.obs[raw_lookup[gene_upper]], errors="coerce").to_numpy(dtype=float)

    if gene_upper in var_lookup:
        idx = adata.var_names.get_loc(var_lookup[gene_upper])
        matrix = adata.layers[layer] if layer is not None and layer in adata.layers else adata.X
        return _matrix_column(matrix, idx).astype(float)

    if gene_upper in raw_lookup:
        return pd.to_numeric(adata.obs[raw_lookup[gene_upper]], errors="coerce").to_numpy(dtype=float)

    return None


def flatten_marker_sets(marker_sets: dict[str, Iterable[str]]) -> list[str]:
    """Flatten marker sets while preserving first occurrence order."""
    seen: set[str] = set()
    markers: list[str] = []
    for genes in marker_sets.values():
        for gene in genes:
            gene_upper = str(gene).upper()
            if gene_upper not in seen:
                seen.add(gene_upper)
                markers.append(gene_upper)
    return markers


def make_figure_plan() -> pd.DataFrame:
    """Return the recommended main-figure panel structure."""
    return pd.DataFrame(
        [
            {
                "panel": "A",
                "question": "どこにいるか",
                "figure": "UMAP: clozapine-response score / responsive cells highlighted",
                "message": "反応細胞がexcitatory neuron領域に偏るかを直感的に見せる",
            },
            {
                "panel": "B",
                "question": "何の細胞か",
                "figure": "Cell-type enrichment odds ratio + 95% CI",
                "message": "Excitatory neuron enrichmentを主張する中心パネル",
            },
            {
                "panel": "C",
                "question": "どのsubtype/layerか",
                "figure": "Layer / excitatory subtype marker dot plot",
                "message": "PFC回路・layer文脈に接続する",
            },
            {
                "panel": "D",
                "question": "なぜ効くのか",
                "figure": "Receptor / cAMP signature violin plot",
                "message": "HTR1A/CHRM2/HRH3やcAMP関連受容体で薬理学的根拠を示す",
            },
            {
                "panel": "E",
                "question": "どんな機能か",
                "figure": "Synapse/plasticity gene-set score or GSEA dot/bar plot",
                "message": "synapse/plasticityは補強材料として使う",
            },
        ]
    )


def cell_type_enrichment_table(
    adata: anndata.AnnData,
    responsive_mask: pd.Series,
    cell_type_col: str,
) -> pd.DataFrame:
    """Compute cell-type enrichment odds ratios for responsive cells."""
    if cell_type_col not in adata.obs:
        return pd.DataFrame()

    mask = np.asarray(responsive_mask, dtype=bool)
    rows = []
    cell_types = pd.Series(adata.obs[cell_type_col].astype(str).values, index=adata.obs_names)
    for cell_type in sorted(cell_types.dropna().unique()):
        in_type = (cell_types == cell_type).to_numpy()
        a = int(np.sum(mask & in_type))
        b = int(np.sum(mask & ~in_type))
        c = int(np.sum(~mask & in_type))
        d = int(np.sum(~mask & ~in_type))
        _, p_value = stats.fisher_exact([[a, b], [c, d]], alternative="two-sided")

        # Haldane-Anscombe correction keeps CI finite when a cell is zero.
        ah, bh, ch, dh = a + 0.5, b + 0.5, c + 0.5, d + 0.5
        odds_ratio = (ah * dh) / (bh * ch)
        se = np.sqrt(1 / ah + 1 / bh + 1 / ch + 1 / dh)
        ci_low = float(np.exp(np.log(odds_ratio) - 1.96 * se))
        ci_high = float(np.exp(np.log(odds_ratio) + 1.96 * se))
        rows.append(
            {
                "cell_type": cell_type,
                "n_responsive_in_type": a,
                "n_responsive_other": b,
                "n_nonresponsive_in_type": c,
                "n_nonresponsive_other": d,
                "odds_ratio": float(odds_ratio),
                "ci_low": ci_low,
                "ci_high": ci_high,
                "p_value": float(p_value),
            }
        )
    return pd.DataFrame(rows).sort_values("odds_ratio", ascending=False).reset_index(drop=True)


def marker_dotplot_table(
    adata: anndata.AnnData,
    responsive_mask: pd.Series,
    marker_sets: dict[str, Iterable[str]] | None = None,
    expression_layer: str = "lognorm",
    positivity_layer: str = "raw_counts",
) -> pd.DataFrame:
    """Compute mean expression and positivity rates for marker dot plots."""
    marker_sets = marker_sets or DEFAULT_LAYER_MARKERS
    mask = np.asarray(responsive_mask, dtype=bool)
    rows = []
    for marker_class, genes in marker_sets.items():
        for gene in genes:
            expr = expression_vector(adata, gene, layer=expression_layer)
            raw = expression_vector(adata, gene, layer=positivity_layer, prefer_obs_raw=True)
            if expr is None and raw is None:
                continue
            if expr is None:
                expr = raw
            if raw is None:
                raw = expr
            for group_name, group_mask in (("clz_responsive", mask), ("non_responsive", ~mask)):
                values = np.asarray(expr[group_mask], dtype=float)
                raw_values = np.asarray(raw[group_mask], dtype=float)
                rows.append(
                    {
                        "marker_class": marker_class,
                        "gene": str(gene).upper(),
                        "group": group_name,
                        "mean_expression": float(np.nanmean(values)) if values.size else np.nan,
                        "pct_positive": float(np.nanmean(raw_values > 0) * 100) if raw_values.size else np.nan,
                        "n_cells": int(values.size),
                    }
                )
    return pd.DataFrame(rows)


def receptor_signature_table(
    adata: anndata.AnnData,
    responsive_mask: pd.Series,
    receptor_sets: dict[str, Iterable[str]] | None = None,
    expression_layer: str = "lognorm",
) -> pd.DataFrame:
    """Summarize receptor/cAMP-related expression signatures by group."""
    receptor_sets = receptor_sets or DEFAULT_RECEPTOR_MARKERS
    mask = np.asarray(responsive_mask, dtype=bool)
    rows = []
    for signature, genes in receptor_sets.items():
        available = []
        for gene in genes:
            vec = expression_vector(adata, gene, layer=expression_layer, prefer_obs_raw=True)
            if vec is not None:
                available.append(vec)
        if not available:
            continue
        score = np.nanmean(np.vstack(available), axis=0)
        for group_name, group_mask in (("clz_responsive", mask), ("non_responsive", ~mask)):
            values = score[group_mask]
            rows.append(
                {
                    "signature": signature,
                    "group": group_name,
                    "mean_score": float(np.nanmean(values)) if values.size else np.nan,
                    "median_score": float(np.nanmedian(values)) if values.size else np.nan,
                    "n_genes_used": len(available),
                    "n_cells": int(values.size),
                }
            )
    return pd.DataFrame(rows)


def functional_gene_set_table(
    adata: anndata.AnnData,
    responsive_mask: pd.Series,
    gene_sets: dict[str, Iterable[str]] | None = None,
    expression_layer: str = "lognorm",
) -> pd.DataFrame:
    """Compare simple average gene-set scores between responsive and non-responsive cells."""
    gene_sets = gene_sets or DEFAULT_FUNCTIONAL_GENESETS
    mask = np.asarray(responsive_mask, dtype=bool)
    rows = []
    for gene_set, genes in gene_sets.items():
        available = []
        for gene in genes:
            vec = expression_vector(adata, gene, layer=expression_layer)
            if vec is not None:
                available.append(vec)
        if not available:
            continue
        score = np.nanmean(np.vstack(available), axis=0)
        selected = score[mask]
        reference = score[~mask]
        if selected.size and reference.size:
            stat, p_value = stats.mannwhitneyu(selected, reference, alternative="two-sided")
        else:
            stat, p_value = np.nan, np.nan
        rows.append(
            {
                "gene_set": gene_set,
                "n_genes_used": len(available),
                "mean_responsive": float(np.nanmean(selected)) if selected.size else np.nan,
                "mean_nonresponsive": float(np.nanmean(reference)) if reference.size else np.nan,
                "median_responsive": float(np.nanmedian(selected)) if selected.size else np.nan,
                "median_nonresponsive": float(np.nanmedian(reference)) if reference.size else np.nan,
                "mean_diff": (float(np.nanmean(selected)) - float(np.nanmean(reference)))
                if selected.size and reference.size
                else np.nan,
                "mannwhitneyu": float(stat) if not np.isnan(stat) else np.nan,
                "p_value": float(p_value) if not np.isnan(p_value) else np.nan,
            }
        )
    return pd.DataFrame(rows).sort_values("mean_diff", ascending=False).reset_index(drop=True)


def plot_umap_response(
    adata: anndata.AnnData,
    responsive_mask: pd.Series,
    output_path: str | Path,
    score_col: str = "cAMP_CLOZAPINE",
) -> None:
    """Save UMAP panels for responsive-cell highlighting and optional response score."""
    if "X_umap" not in adata.obsm:
        return
    umap = np.asarray(adata.obsm["X_umap"])
    if umap.shape[1] < 2:
        return

    plot_df = pd.DataFrame({
        "UMAP1": umap[:, 0],
        "UMAP2": umap[:, 1],
        "clz_responsive": np.asarray(responsive_mask, dtype=bool),
    })
    if score_col in adata.obs:
        plot_df[score_col] = pd.to_numeric(adata.obs[score_col], errors="coerce").to_numpy(dtype=float)

    ncols = 2 if score_col in plot_df else 1
    fig, axes = plt.subplots(1, ncols, figsize=(5 * ncols, 4.5))
    if ncols == 1:
        axes = [axes]

    sns.scatterplot(
        data=plot_df,
        x="UMAP1",
        y="UMAP2",
        hue="clz_responsive",
        palette={False: "lightgray", True: "red"},
        s=5,
        linewidth=0,
        ax=axes[0],
    )
    axes[0].set_title("Clozapine-responsive cells")
    axes[0].set_xlabel("UMAP1")
    axes[0].set_ylabel("UMAP2")

    if ncols == 2:
        sc = axes[1].scatter(
            plot_df["UMAP1"],
            plot_df["UMAP2"],
            c=plot_df[score_col],
            s=5,
            linewidths=0,
            cmap="viridis",
        )
        axes[1].set_title(score_col)
        axes[1].set_xlabel("UMAP1")
        axes[1].set_ylabel("UMAP2")
        fig.colorbar(sc, ax=axes[1], label=score_col)

    fig.tight_layout()
    fig.savefig(output_path, dpi=200)
    plt.close(fig)


def plot_cell_type_enrichment(enrichment_df: pd.DataFrame, output_path: str | Path) -> None:
    """Save odds-ratio forest plot for cell-type enrichment."""
    if enrichment_df.empty:
        return
    plot_df = enrichment_df.sort_values("odds_ratio")
    fig, ax = plt.subplots(figsize=(6, max(3, 0.35 * len(plot_df))))
    ax.errorbar(
        plot_df["odds_ratio"],
        plot_df["cell_type"],
        xerr=[plot_df["odds_ratio"] - plot_df["ci_low"], plot_df["ci_high"] - plot_df["odds_ratio"]],
        fmt="o",
        color="black",
        ecolor="gray",
    )
    ax.axvline(1, linestyle="--", color="red", linewidth=1)
    ax.set_xscale("log")
    ax.set_xlabel("Odds ratio among clozapine-responsive cells")
    ax.set_ylabel("")
    fig.tight_layout()
    fig.savefig(output_path, dpi=200)
    plt.close(fig)


def plot_marker_dotplot(marker_df: pd.DataFrame, output_path: str | Path) -> None:
    """Save marker dot plot: dot size = pct positive, color = mean expression."""
    if marker_df.empty:
        return
    plot_df = marker_df.copy()
    plot_df["gene_label"] = plot_df["marker_class"] + ":" + plot_df["gene"]
    fig, ax = plt.subplots(figsize=(5, max(4, 0.25 * plot_df["gene_label"].nunique())))
    sns.scatterplot(
        data=plot_df,
        x="group",
        y="gene_label",
        size="pct_positive",
        hue="mean_expression",
        sizes=(20, 220),
        palette="viridis",
        ax=ax,
    )
    ax.set_xlabel("")
    ax.set_ylabel("")
    ax.legend(bbox_to_anchor=(1.02, 1), loc="upper left")
    fig.tight_layout()
    fig.savefig(output_path, dpi=200)
    plt.close(fig)


def run_clz_responsive_figure_story(
    adata: anndata.AnnData,
    group_col: str = "is_clz_selective",
    positive_label=True,
    cell_type_col: str | None = None,
    output_dir: str = "outputs/clz_responsive_figures",
    expression_layer: str = "lognorm",
    positivity_layer: str = "raw_counts",
) -> ClzResponsiveFigureResult:
    """Run notebook-friendly analyses and print a conversational figure plan.

    The function saves tables and plots under ``output_dir`` and returns all
    generated tables for further ipynb exploration.
    """
    if group_col not in adata.obs:
        raise KeyError(f"{group_col!r} is not present in adata.obs")

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    responsive_mask = _as_bool_mask(adata.obs[group_col], positive_label=positive_label)
    n_responsive = int(responsive_mask.sum())
    n_reference = int((~responsive_mask).sum())

    _print_dialogue(
        "メインメッセージは『何者か』と『なぜ効くのか』を分けると伝わりやすいです。"
    )
    print(f"Responsive cells: {n_responsive:,}")
    print(f"Non-responsive cells: {n_reference:,}")

    figure_plan = make_figure_plan()
    figure_plan.to_csv(output_path / "figure_plan.csv", index=False)
    print("\nRecommended main figure panels:")
    print(figure_plan.to_string(index=False))

    _print_dialogue("Panel A: UMAP上でclozapine-responsive cells / cAMP_CLOZAPINE scoreを可視化します。")
    plot_umap_response(adata, responsive_mask, output_path / "umap_clz_responsive.png")

    if cell_type_col is None:
        candidates = ["cell_type", "celltype", "cell_type_label", "annotation", "subclass", "label", "leiden"]
        cell_type_col = next((col for col in candidates if col in adata.obs), None)

    if cell_type_col is None:
        _print_dialogue("cell type列が見つからないので、Panel Bはannotation列を指定して再実行してください。")
        enrichment_df = pd.DataFrame()
    else:
        _print_dialogue(f"Panel B: {cell_type_col!r} ごとにclozapine-responsive enrichmentを計算します。")
        enrichment_df = cell_type_enrichment_table(adata, responsive_mask, cell_type_col)
        enrichment_df.to_csv(output_path / "cell_type_enrichment.csv", index=False)
        plot_cell_type_enrichment(enrichment_df, output_path / "cell_type_enrichment_odds_ratio.png")
        if not enrichment_df.empty:
            print(enrichment_df.head(10).to_string(index=False))

    _print_dialogue("Panel C: excitatory / layer marker dot plot用の平均発現量と陽性率を計算します。")
    marker_df = marker_dotplot_table(
        adata,
        responsive_mask,
        expression_layer=expression_layer,
        positivity_layer=positivity_layer,
    )
    marker_df.to_csv(output_path / "layer_marker_dotplot_table.csv", index=False)
    plot_marker_dotplot(marker_df, output_path / "layer_marker_dotplot.png")

    _print_dialogue("Panel D: HTR1A/CHRM2/HRH3 と cAMP関連 receptor signature を要約します。")
    receptor_df = receptor_signature_table(adata, responsive_mask, expression_layer=expression_layer)
    receptor_df.to_csv(output_path / "receptor_signature_summary.csv", index=False)
    if not receptor_df.empty:
        print(receptor_df.to_string(index=False))

    _print_dialogue("Panel E: synapse/plasticity/cAMP gene-set scoreを反応群 vs 非反応群で比較します。")
    functional_df = functional_gene_set_table(adata, responsive_mask, expression_layer=expression_layer)
    functional_df.to_csv(output_path / "functional_gene_set_summary.csv", index=False)
    if not functional_df.empty:
        print(functional_df.to_string(index=False))

    _print_dialogue(
        "結論: UMAP + cell-type OR + layer marker + receptor/cAMP signature + synapse/plasticity の順で見せるのがおすすめです。"
    )
    print(f"Saved outputs to: {output_path}")

    return ClzResponsiveFigureResult(
        output_dir=str(output_path),
        figure_plan=figure_plan,
        cell_type_enrichment=enrichment_df,
        marker_dotplot=marker_df,
        receptor_signature=receptor_df,
        functional_gene_sets=functional_df,
    )
